import './Passport.css';

const Passport = () => {
  return (
    <article data-cy='passport-container' className='passport-container'>Steps:
      <div data-cy='passport-doc' className='passport-doc'>
        <p>***Please refer to Incident Overview to obtain on-site protocol for a particular Incident***</p>
        <p>A. Early Warning – Early warning refers to arrangements to rapidly disseminate
        information concerning imminent threats to government
        officials, institutions, and the population at large in the areas at immediate risk.
        These warnings normally are generated by new systems such as TriNet, discussed
        in Session 6. While the warning systems only begin when earthquake shaking
        starts, it may allow actions such as moving to safer locations or shutting off of gas
      lines, etc.</p>
        <p>B. Evacuation/migration – Evacuation involves the relocation of a population from
        zones at risk of an imminent disaster to a safer location, especially if structures are
      susceptible to damage from aftershock.</p>
        <p>C. Search and rescue – Search and rescue (SAR), is the process of identifying the
        location of disaster victims who may be trapped or isolated and bringing them to
        safety and medical attention. In the aftermath focus on locating people who are trapped and injured in collapsed buildings.</p>
        <p>D. Post-disaster assessment – The primary objective of assessment is to provide a
        clear, concise picture of the post-disaster situation, to identify relief needs, and to
        develop strategies for recovery. It determines options for humanitarian assistance,
        how best to utilize existing resources, or to develop requests for further assistance.
        The post-disaster assessment must distinguish among pre-disaster chronic
      conditions, the needs of disaster survivors and their resources.</p>
        <p>E. Emergency relief – Emergency relief is the provision, on a humanitarian basis, of
        material aid and emergency medical care necessary to save and preserve human
        lives. It also enables families to meet their basic needs for medical and health
        care, shelter, clothing, water, and food (including the means to prepare food).
        Relief supplies or services typically are provided, free of charge, in the days and
      weeks immediately following a sudden disaster.</p>
        <p>F. Logistics and supply – The delivery of emergency relief will require logistical
        facilities and capacity. A well-organized supply service is crucial for handling the
        procurement or donation, storage, and dispatch of relief supplies for distribution to
      disaster victims.</p>
        <p>G. Communication and information management – All of the above activities are
        dependent on communication. There are two key aspects to communications in
      disasters.</p>
        <p> 1. The equipment essential for information flow, such as radios, telephones,
        and their supporting systems of repeaters, satellites, and transmission
        lines.</p>
        <p> 2. The information management,that is, the protocol of knowing who
        communicates what information to whom, what priority is given to it, and
          how it is disseminated and interpreted.</p>
        <p>H. Survivor response and coping – In the rush to plan and execute a relief operation,
            it is easy to overlook the real needs and resources of the survivors.</p>
        <p> 1. The assessment must take into account existing social coping mechanisms
              that negate the need to bring in outside assistance.</p>
        <p>I. Security – Security is not always a priority issue after sudden onset natural
        disasters. Typically, it is handled by civil defense or police departments.</p>
        <p>J. Emergency operations management – None of the above activities can be
        implemented without some degree of emergency operations management.
        Policies and procedures for management requirements need to be established well
        in advance of the disaster.</p>
        <p>K. Rehabilitation and reconstruction – Rehabilitation and reconstruction complete
        the disaster response activities and merge with the recovery phase. </p>
        <p>CATEGORIES IN RESPONSE PLAN / COMMUNITY UPDATES: </p>
        <p>A. Health Services.</p>
        <p>B. Emergency Social Services.</p>
        <p>C. Law and Order.</p>
        <p>D. Heavy Urban Search and Rescue.</p>
        <p>E. Communications.</p>
        <p>F. Damage Assessment.</p>
        <p>G. Firefighting/Rescue.</p>
        <p>H. Transportation.</p>
        <p>I. Engineering and Construction.</p>
        <p>J. Human Resources.</p>
        <p>K. Coroner/Mortuary.</p>
        <p>L. Hazardous Materials.</p>
        <p>M. Public Information.</p>
        <p>N. Food and Agriculture.</p>
        <p>O. Finance and Insurance.</p>
        <p>P. Utilities. </p>
      </div>
    </article>
  )
}
export default Passport;